ISSUE-182: Make Metadata Display Entities Revisionable
esmero/format_strawberryfield pull request #183
Opened 2022-03-28 19:43 UTC by aksm

Beginning work on #182 (basically just dropped in code from the Drupal docs mentioned in the issue).

2022-03-28 19:56 UTC, DiegoPino requested changes
A few changes that came from the copy

2022-03-28 19:56 UTC, DiegoPino commented on format_strawberryfield.install
> +function my_module_update_8400() {
This function needs to be named format_strawberryfield_ (replace the my_module with this module's name) and the numbering needs to be something after the previous one which was 

`function format_strawberryfield_update_8702() `

So format_strawberryfield_update_8703?

2022-03-28 19:56 UTC, DiegoPino commented on format_strawberryfield.install
> +    $dependencies['format_strawberryfield'][8400] = [
Same here, 8400 needs to be 8703, etc

2022-03-28 19:56 UTC, DiegoPino commented on src/Entity/MetadataDisplayEntity.php
> + *     "published" = "status"
👍

2022-03-28 19:56 UTC, DiegoPino commented on src/Entity/MetadataDisplayEntity.php
> +      ->setDescription(t('The time that the term was last edited.'))
Not a term!

2022-03-29 13:15 UTC, DiegoPino commented on src/Entity/MetadataDisplayEntity.php
> +      ->setDescription(t('The time that the term was last edited.'))
Nothing is stupid, I appreciate the quick response and the learning path you have taken

2022-06-15 19:12 UTC, aksm commented
Going to close this and start fresh from 1.0.0 since I have a better understanding of Drupal now.

2022-06-15 19:12 UTC, closed without merging